[build]
  base = ""
  command = 'sed -i "s|not-configured|${DEPLOY_PRIME_URL}|g" netlify.toml && npm run build'
  publish="/build"


[context.production]
  environment = { REACT_APP_ENVIRONMENT = "https://google.com", REACT_APP_CONFIGURABLE = "not-configured" }

[context.staging]
  environment = { REACT_APP_ENVIRONMENT = "https://staging.google.com", REACT_APP_CONFIGURABLE = "not-configured" }

[context.deploy-preview]
  environment = { REACT_APP_ENVIRONMENT = "https://test.google.com", REACT_APP_CONFIGURABLE = "not-configured" }
